services:
  ros2:
    build:
      context: docker/Dockerfile
    image: ros2_humble
    container_name: ros2_humble
    network_mode: host
    ipc: host
    privileged: true
    gpus: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ../workspace:/workspace
      - ../data:/data
      - ../scripts/record.sh:/record.sh
      - ../scripts/topics_lists:/topics_lists

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    working_dir: /workspace

    tty: true
    stdin_open: true
    entrypoint: []

  carla:
    image: carlasim/carla:0.9.16
    container_name: carla
    network_mode: host
    ipc: host
    gpus: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ../import:/workspace/Import
      - ./entrypoint_carla.sh:/entrypoint_carla.sh

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    shm_size: "8g"

    tty: true
    stdin_open: true
    entrypoint: ["bash", "/entrypoint_carla.sh"]
